# Meta Data for SEO

## Homepage
title = "lnquy"
titleSeparator = "-"
titleAddition = "Fight the cargo cult"
description = "lnquy is a personal blog that helps noting down everything I've learned or just simply a place for ranting, sometimes."

## Open Graph + Twitter Cards
# images = ["doks.png"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
# ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/"
schemaLinkedIn = "https://www.linkedin.com/in/"
schemaGitHub = "https://github.com/lnquy"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
bgColor = "#fff"
landscapePhotoWidths = [1000, 900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
# %dx is the width size of image src, which will be fill-in by Hugo later.
# q85 is the quality of resized images.
imageResizeQuality = "%dx q90"

# Footer
footer = "Quy Le © 2021. Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/lnquy/www"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = true
  highLight = true
  kaTex = false
